-- MEMBER 테이블 생성

CREATE TABLE MEMBER (
	MEM_ID	VARCHAR2(20) NOT NULL UNIQUE,
	MEM_ROLE VARCHAR2(10) NULL,
	MEM_NAME VARCHAR2(10) NOT NULL,
	MEM_PWD	VARCHAR2(20)	NOT NULL,
	MEM_EMAIL VARCHAR2(50) NOT NULL,
	MEM_PHONE NUMBER NOT NULL,
	MEM_ADDR VARCHAR2(100) NOT NULL,
	MEM_BIRTH VARCHAR2(20) NOT NULL,
	CREATE_DATE	DATE DEFAULT SYSDATE,
	MODIFY_DATE	DATE DEFAULT SYSDATE,
	STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);

-- MEMBER 테이블 코맨트
COMMENT ON COLUMN MEMBER.MEM_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEM_ROLE IS '회원타입';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.MEM_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEM_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.MEM_PHONE IS '휴대전화';
COMMENT ON COLUMN MEMBER.MEM_ADDR IS '회원주소';
COMMENT ON COLUMN MEMBER.MEM_BIRTH IS '생년월일';
COMMENT ON COLUMN MEMBER.CREATE_DATE IS '생성날짜';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '수정날짜';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값(Y/N)';

-- 관리자 정보 생성
INSERT INTO MEMBER VALUES (
    'admin',
    'ROLE,ADMIN',
    '관리자',
    '1234',
    'CAREPOOL@NAVER.COM',
    '010-0000-0000',
    '서울시',
    '1993/00/00',
    SYSDATE,
    SYSDATE,
    DEFAULT
);

-- 임의의 회원 생성
INSERT INTO MEMBER VALUES (
    'asdf',
    'ROLE,USER',
    '홍길동',
    '1234',
    'CARE@NAVER.COM',
    '010-1020-0000',
    '서울시',
    '1999/10/20',
    SYSDATE,
    SYSDATE,
    DEFAULT
);

----------------------------------------------------------------------
-- 보호자 생성
CREATE TABLE GUARDIAN_PROFILE (
	GUARD_NO NUMBER	NOT NULL,
	GUARD_GEN VARCHAR2(2) NOT NULL,
	GUARD_PAT VARCHAR2(10) NOT NULL,
	MEM_ID	VARCHAR2(20) NOT NULL
);
-- 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD_NO;
-- 보호자 번호 PK등록
ALTER TABLE GUARDIAN_PROFILE ADD CONSTRAINT PK_GUARDIAN_PROFILE PRIMARY KEY (
	GUARD_NO
);

--ALTER TABLE GUARDIAN_PROFILE MODIFY GUARD_GEN CHAR(3) CHECK(GUARD_GEN IN('남','여'));

-- 회원 아이디 외래키 등록
ALTER TABLE GUARDIAN_PROFILE ADD CONSTRAINT FK_member_TO_guardian_profile FOREIGN KEY (
	MEM_ID
)
REFERENCES member (
	MEM_ID
);
-- 보호자프로필 코맨트 등록
COMMENT ON COLUMN GUARDIAN_PROFILE.GUARD_NO IS '보호자번호';
COMMENT ON COLUMN GUARDIAN_PROFILE.GUARD_GEN IS '성별';
COMMENT ON COLUMN GUARDIAN_PROFILE.GUARD_PAT IS '(보호자/환자)';

-- 보호자 프로필 생성
INSERT INTO guardian_profile VALUES(
    SEQ_BOARD_NO.NEXTVAL,
    '남',
    '환자',
    'asdf'
);
-- MEMBER 와 조인해서 정보 확인
SELECT MEM_PHONE, GUARD_GEN
FROM MEMBER M
JOIN guardian_profile G ON(M.MEM_ID = G.MEM_ID);

CREATE TABLE patient_details (
	pat_no NUMBER NOT NULL,
	guard_no NUMBER	NOT NULL,
	pat_guard VARCHAR2(30) NULL,
	pat_name VARCHAR2(20) NULL,
	pat_age	NUMBER NULL,
	pat_gen	CHAR(3) NULL CHECK(pat_gen IN('남','여')),
	pat_kg	NUMBER NULL,
	pat_place VARCHAR2(200) NULL,
	pat_period DATE	NULL,
    pat_hop_time DATE,
	pat_grade NUMBER NULL,
	pat_infect VARCHAR2(50)	NULL,
	pat_sanit VARCHAR2(50) NULL,
	pat_paral VARCHAR2(50) NULL,
	pat_move VARCHAR2(50) NULL,
	pat_bed	VARCHAR2(50) NULL,
	pat_cogdis VARCHAR2(50)	NULL,
	pat_bathroom VARCHAR2(50) NULL,
	pat_bowel_mn VARCHAR2(50) NULL,
	pat_ostomy	VARCHAR2(50) NULL,
	pat_help_eat VARCHAR2(50) NULL,
	pat_suction VARCHAR2(50) NULL,
	pat_guard_gen CHAR(3) CHECK(pat_guard_gen IN('남','여')) NULL,
	pat_etc	VARCHAR2(1000) NULL
);
--DROP TABLE patient_details;

ALTER TABLE patient_details ADD CONSTRAINT PK_PATIENT_DETAILS PRIMARY KEY (
	pat_no
);
--컬럼 추가 문
--ALTER TABLE patient_details ADD pat_hop_time DATE;
-- 2) 제약조건 추가/삭제
--      2-1) 제약조건 추가
--        PRIMARY KEY : ALTER TABLE 테이블명 ADD [CONSTRAINT 제약조건명] PRIMARY KEY(컬럼명);
--        FOREIGN KEY : ALTER TABLE 테이블명 ADD [CONSTRAINT 제약조건명] FOREIGN KEY(컬럼명) REFERENCES 참조할테이블명 [(컬럼명)];
--        UNIQUE      : ALTER TABLE 테이블명 ADD [CONSTRAINT 제약조건명] UNIQUE(컬럼명)
--        CHECK       : ALTER TABLE 테이블명 ADD [CONSTRAINT 제약조건명] CHECK(컬럼에대한 조건)
--        NOT NULL    : ALTER TABLE 테이블명 MODIFY 컬럼명 [CONSTRAINT 제약조건명] NOT NULL;

ALTER TABLE patient_details ADD CONSTRAINT FK_GUARD_TO_PAT_DETAIL FOREIGN KEY (
	guard_no
)
REFERENCES guardian_profile(
	guard_no
);

COMMENT ON COLUMN PATIENT_DETAILS.PAT_NO IS '환자번호';
COMMENT ON COLUMN PATIENT_DETAILS.guard_no IS '보호자번호';
COMMENT ON COLUMN PATIENT_DETAILS.pat_name IS '이름';
COMMENT ON COLUMN PATIENT_DETAILS.pat_age IS '나이';
COMMENT ON COLUMN PATIENT_DETAILS.pat_gen IS '성별';
COMMENT ON COLUMN PATIENT_DETAILS.pat_kg IS '몸무게';
COMMENT ON COLUMN PATIENT_DETAILS.pat_place IS '돌봄장소(자택/병원)';
COMMENT ON COLUMN PATIENT_DETAILS.pat_period IS '돌봄기간';
COMMENT ON COLUMN PATIENT_DETAILS.pat_hop_time IS '희망시간';
COMMENT ON COLUMN PATIENT_DETAILS.pat_grade IS '요양등급';
COMMENT ON COLUMN PATIENT_DETAILS.pat_infect IS '감염성질환';
COMMENT ON COLUMN PATIENT_DETAILS.pat_sanit IS '개인위생';
COMMENT ON COLUMN PATIENT_DETAILS.pat_paral IS '마비상태';
COMMENT ON COLUMN PATIENT_DETAILS.pat_move IS '거동상태';
COMMENT ON COLUMN PATIENT_DETAILS.pat_bed IS '욕창환자여부(예/아니요)';
COMMENT ON COLUMN PATIENT_DETAILS.pat_cogdis IS '인지장애여부';
COMMENT ON COLUMN PATIENT_DETAILS.pat_bathroom IS '화장실이동';
COMMENT ON COLUMN PATIENT_DETAILS.pat_bowel_mn IS '배변도구';
COMMENT ON COLUMN PATIENT_DETAILS.pat_ostomy IS '장루설치여부';
COMMENT ON COLUMN PATIENT_DETAILS.pat_help_eat IS '식사도움여부';
COMMENT ON COLUMN PATIENT_DETAILS.pat_suction IS '석션사용여부';
COMMENT ON COLUMN PATIENT_DETAILS.pat_guard_gen IS '우대성별';
COMMENT ON COLUMN PATIENT_DETAILS.pat_etc IS '기타사항';

--COMMIT;